apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-reg-pvc
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: "nfs"
