apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-volume
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  nfs:
    server: 192.168.10.5
    path: /opt/exports/nfs/k8s/redis-kubernetes_the_hard_way
    readOnly: no
