apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: helloredis
  name: redis-pv-claim
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: "nfs"
